// Multi-language Hello World (100+ languages)

const greetings = {
  en: "Hello",
  es: "Hola",
  fr: "Bonjour",
  de: "Hallo",
  it: "Ciao",
  pt: "Olá",
  ru: "Привет",
  zh: "你好",
  ja: "こんにちは",
  ko: "안녕하세요",
  hi: "नमस्ते",
  ar: "مرحبا",
  bn: "হ্যালো",
  ur: "ہیلو",
  tr: "Merhaba",
  nl: "Hallo",
  sv: "Hej",
  fi: "Hei",
  da: "Hej",
  no: "Hei",
  el: "Γειά σου",
  he: "שלום",
  pl: "Cześć",
  cs: "Ahoj",
  sk: "Ahoj",
  ro: "Salut",
  hu: "Szia",
  th: "สวัสดี",
  vi: "Xin chào",
  id: "Halo",
  ms: "Hai",
  ta: "வணக்கம்",
  te: "హలో",
  kn: "ನಮಸ್ಕಾರ",
  ml: "നമസ്കാരം",
  pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
  si: "හෙලෝ",
  fa: "سلام",
  sw: "Habari",
  af: "Hallo",
  sq: "Përshëndetje",
  hr: "Bok",
  sr: "Здраво",
  bg: "Здравей",
  uk: "Привіт",
  lv: "Sveiki",
  lt: "Labas",
  et: "Tere",
  is: "Halló",
  ga: "Dia dhuit",
  cy: "Helo",
  mk: "Здраво",
  bs: "Zdravo",
  sl: "Živjo",
  mt: "Ħelow",
  ht: "Bonjou",
  jv: "Halo",
  su: "Halo",
  lo: "ສະບາຍດີ",
  km: "សួស្តី",
  my: "မင်္ဂလာပါ",
  ne: "नमस्कार",
  am: "ሰላም",
  yo: "Bawo",
  ig: "Ndewo",
  ha: "Sannu",
  zu: "Sawubona",
  xh: "Molo",
  st: "Lumela",
  tn: "Dumela",
  sn: "Mhoro",
  rw: "Muraho",
  mg: "Salama",
  eu: "Kaixo",
  gl: "Ola",
  eo: "Saluton",
  la: "Salve",
  ku: "Slav",
  ps: "سلام",
  ky: "Салам",
  uz: "Salom",
  kk: "Сәлем",
  mn: "Сайн байна уу",
  tk: "Salam",
  bo: "བཀྲ་ཤིས་",
  ug: "ياخشىمۇسىز",
  gae: "Hàlo",
  oc: "Bon jorn",
  lb: "Moien",
  br: "Demat",
  fy: "Hoi",
  mi: "Kia ora",
  sm: "Talofa",
  to: "Malo e lelei",
  fj: "Bula",
  haw: "Aloha",
  chr: "ᎣᏏᏲ",
  nv: "Yáʼátʼééh",
  oj: "Boozhoo",
  cre: "Tansi",
  tlh: "nuqneH", // Klingon, just for fun 😉
};

/**
 * Say hello in multiple languages.
 * @param {string} name - Name to greet.
 * @param {string} lang - Language code (ISO 639-1).
 * @returns {string}
 */
function hello(name = "world", lang = "en") {
  const greeting = greetings[lang.toLowerCase()] || greetings["en"];
  return `${greeting}, ${name}!`;
}

module.exports = { hello };
